

# key: nameSafe of hero
# value: List where
# 0 is list of pvp runes,
# 1 is Primary stat,
# 2 is Secondary stat,
# 3 is Notes
# 4 is PVP Tier
# 5 is info

heroDict = {
        "akwa": [["vitality", "runeSwift", "damage", "precise", "rage"], "APS, ATK, Crit DMG", "Attack Range", "Base of 200, whatever is required to stay behind your front line tanks", "A", "Akwa is kind of a niche hero. Her buff is water attack speed, so she’s usually paired up with either Atlantus or a freeze group with heroes such as Frost Queen, Namida, Snowman, and Pirato. She has decent enough HP and Def to survive in the front line, as long as she is not the very front. She also does decent damage. Her sp2 has pushback, which can slow down the dps of backline heroes. "],
        "alda": [["damage", "runeSwift", "precise", "rage"], "ATK, APS, Crit DMG", "Attack Range", "Needs 35.2% to get to 750 range", "S", "Alda is one of the Crit Sisters. She and Valkyrie are able to give Crit buffs to everyone and are fondly known as the Crit Sisters. This makes her very good in both the Slay Event and PVP. Alda is not in any Crusher Chests, which makes her difficult to obtain."],
        "angelica": [["intelligent"], "Nothing specific", "Nothing specific", "-", "-", "The lackluster Legendary. At 3 star Angelica is useful in the Guild Slay Event because her Ultimate doubles the attack of your team. It also applies a shield, which may help too. She has the lowest dps in the game, which basically makes her useless in PVP. She can resurrect fallen heroes, but it’s not enough to add her to your Arena team. Since her only real use is her ultimate in the Slay Event, give her weapon level 3 with Intelligent, and be done with her."],
        "arcana": [["stunning"], "Nothing specific", "Nothing specific", "-", "C", "Arcana is a mediocre rare hero. Crit buffers are nice for the Guild Slay Event and blitz, but since she only buffs Light heroes, it doesn’t translate over to Arena unless you are starting with Spike. Light doesn’t have enough dps heroes to justify using a Light only Crit buffer for Arena."],
        "atlantus": [["vitality", "damage", "runeSwift", "precise"], "AoE, ATK, APS, Crit DMG", "Attack Range", "70-150% AoE. Base Range of 220, get whatever is required to stay behind your front line tanks", "A", "Atlantus is an front line AoE smasher with great damage potential. He is immune to stun, which is very useful with all the Monki King’s flying around in Diamond and Legendary. He has his own Crusher Chest, which means you can increase his stars fairly easily."],
        "bat": [["damage", "runeSwift", "precise", "rage"], "ATK, Crit DMG, APS", "Nothing specific", "-", "C", "Bat was the best common that is not a tank until Dragon Bot was released. Bat is a very good choice for your 4th common to get to 7. Bat has very good dps for a common, but as a 4th hero, he may not make it to your arena team. He will still be very useful in GW and Blitz."],
        "blackBeard": [["vitality"], "HP", "Nothing specific", "-", "C", "Below average HP for a Knight. He’s mostly used as a Tank for Blitz."],
        "bunGun": [["runeSwift", "stunning", "dazed"], "APS, AoE, Stun duration", "Attack Range", "Needs 78.5% to get to 750 range", "A", "Bungun has a lot of potential. Her problem is that she is an event hero, and therefore very difficult to get to high stars. You can use her at low as a crowd control hero. She does AoE, so she can crowd control the front line. Her other downfall is that she doesn’t have a whole lot of base attack range, so she can be difficult to keep alive."],
        "chaos": [["vitality", "damage", "runeSwift", "precise", "rage"], "APS, ATK, Crit DMG, AoE", "Attack Range", "Base range of 220, whatever is required to stay behind your front line tanks", "B", "Chaos is the front line killer. His sp2 is a small aoe that can be devastating to a front line group. Once people start using fewer front line heroes, his usefulness decreases, as his 1v1 damage isn’t as good. The all dark teams love this guy, as there are not a lot of choices for dark tanks outside of Ornok. Most people use him as the front line DPS. You’ll need the vitality set for survival on the front line. Then your choice of Damage, Precise, Swift, and Rage."],
        "circe": [["vitality"], "Nothing specific", "Nothing specific", "Doesn’t need any runes to be effective. Vitality can be used for survivability", "C", "Circe is a Halloween event hero, who can be very annoying to fight. She possesses opponent heroes to fight for her. These heroes cannot use their sp2 for her, just their sp1, but once she starts possessing your main hero, it can be devastating. There is a lot of RNG on how well she will help a team in any given battle. Early on she’s great to add to any team, but later on she becomes less useful. "],
        "clawdette": [["vitality", "damage", "runeSwift"], "APS, Crit DMG, ATK", "Attack Range", "Base range of 160, whatever is required to stay behind your front line tanks", "B", "Clawdette is mostly used for her 20% trophy bonus in blitz. As a brawler, her damage increases with her combo. This increases both her raw damage and her poison damage. Her poison damage is nice because it bypasses Def, and most End Game tanks have a lot of Def. Her team buff also buffs poison which further helps her poison, but is also great when paired with Thorn, for his poison damage."],
        "darkHunter": [["damage", "runeSwift", "precise", "rage"], "APS, ATK, Crit DMG", "Attack Range", "Needs 27,1% to get 750 range", "S", "Dark Hunter is one of the best PVP heroes in the game and is extremely easy to add to any team. His team buff decreases the opponent’s attack, which is pretty much required to keep your tanks alive. He has the best atk and raw dps of any ranger, and of any back line dps. He has the second highest base Attack Range, which means he is very easy to keep alive. He also has 25% base crit rate, which is one of the highest in the game."],
        "darkKnight": [["vitality"], "HP", "Movement speed", "-", "-", "Dark Knight is mostly used as a blitz tank. In blitz, all you really need is the vitality set. All dark teams can pull him off as a tank with Vitality, Phalanx, and Nimble, with HP primaries."],
        "darkWolf": [["runeSwift", "stunning", "dazed"], "Nothing specific", "Nothing specific", "No runes are required, you just use him for his team buff.", "C", "Dark Wolf is a niche PVP hero. He is usually paired with Hikari or another movement speed buffer. Dark Wolf decreases opponent movement speed, and Hikari increases your team’s movement speed. These two heroes combined can keep the opponent’s team near their crystal. This nerfs any attack range buffs. It also allows your aoe to hit their crystal, and possibly defeat them without killing all their heroes. It’s somewhat of a trick tactic that you need to watch out for."],
        "dragonBot": [["damage", "runeSwift", "precise", "rage"], "APS, ATK, Crit DMG", "Nothing specific", "-", "B", "Dragon Bot is the best common that is not a tank. He is a very good choice for your 2nd or 3rd common to get to 7 stars. While Bat has more base dps, DB will usually out damage Bat since he is a gunner and therefore ignores 70% of def. DB also lowers the opponent’s front line hero atk, which is very important early game to keep your main tank alive."],
        "frostQueen": [["chilling", "splash"], "AoE, APS", "Attack Range", "Needs 44.2% to get to 750 range", "A", "Freeze Explode! Frost Queen has Freeze Explode, and this has huge potential. Once she reaches 4, all freezes, whether caused by her or another hero, will explode. Before 4, only freezes initiated by Frost Queen will explode. If you give her chilling, all initial freeze explosions can freeze and explode again. They cannot chain further than that. There are some really strong builds that freeze most of the opponents for most of the time. The problem is a team built around freeze explode requires a lot of good runes."],
        "furiosa": [["vitality", "phalanx", "nimble"], "HP", "Movement speed", "Avoid attack range", "B", "Furiosa is the best hero for slay event. She’s immune to freeze which is handy against Frost Queen teams, so she has a place in PvP. If you want to be a strong Slay Event hitter, use Swift, Precise, and Frenzy with attack speed primaries. For PVP, she’s mostly used as a tank, so use Vitality, Phalanx, and Nimble, with HP primaries."],
        "gladiator": [["vitality", "guard", "nimble"], "HP", "Movement speed, Def", "Avoid attack range", "A", "The main f2p tank of the current meta, Gladiator has a ton of HP. He also has a significant amount of def. Leaf Blade, Ornok, and Paladin are the only tanks ranked higher. Once you get 1 or 2 commons to 7, it is time to start using Magic Medals on Gladiator. While you can technically use Gladiator as a front line AOE smasher, almost everyone uses him as a Pure Tank."],
        "goddess": [["noRune"], "Nothing specific", "Nothing specific", "-", "-", "Don't spend materials on this hero, but Goddess is nice because her sp2 has push back, which helps early game and in blitz. She doesn’t need runes, but chilling can give her tidal wave a chance to freeze each hero it hits. She is also useful in the Guild Slay Event, as her Ultimate is a shield that is very helpful to keep heroes alive."],
        "goldKnight": [["vitality"], "HP", "Movement speed", "-", "-", "Gold Knight can be a decent tank in Blitz. His team buff is movement speed, which is helpful for a mostly Light team in blitz. This can push back the opponent closer to their crystal, and allow aoe heroes like Spike and Siegfried to hit the crystal, if they have enough AOE. Other than blitz, there’s not much use for Gold Knight."],
        "greenFaery": [["noRune"], "Nothing specific", "Nothing specific", "-", "-", "Green Faery adds a protective shield to a random hero for her sp2. This guarantees at least one extra hit, and for the slay event, this can be useful for survivor builds, especially for the Nimble Knights build. It’s not that helpful in PVP. She’s not that good, one of the worst epics in the game."],
        "groovine": [["intelligent"], "Nothing specific", "Nothing specific", "-", "C", "Groovine is a crusher with a relatively poor quality crusher chest. Her ultimate turns other elemental damage (other than fire) into earth damage. This is very useful against water bosses in the Guild Slay Event."],
        "hikari": [["frenzy"], "Nothing specific", "Nothing specific", "Frenzy for staging", "-", "Hikari is a niche PVP hero. He is usually paired with Dark Wolf. Dark Wolf decreases opponent movement speed, and Hikari increases your team’s movement speed. These two heroes combined can keep the opponent’s team near their crystal. This nerfs any attack range buffs. It also allows your aoe to hit their crystal, and possibly defeat them without killing all their heroes. It’s somewhat of a trick tactic that you need to watch out for. No runes are required, you just use him for his team buff."],
        "hooky": [["noRune"], "Nothing specific", "Nothing specific", "-", "C", "Don't spend materials on this hero. Hooky is a relatively new Blitz Hero. His damage isn’t that great. His team buff increase earth attack range, and not many people use a lot of earth heroes. In addition, you can get all your required attack range from runes. His sp2 pulls opponent heroes nearer, which can help, but doesn’t seem to be enough to use him."],
        "iceCube": [["vitality", "chilling", "runeSwift", "damage"], "HP", "Nothing specific", "-", "B", "Ice Cube has some potential, but is extremely difficult to get medals for. His team buff isn’t great, and having a good team buff is very important for high Tier PVP heroes."],
        "iceKnight": [["chilling", "frozen", "vitality", "phalanx"], "Nothing specific", "Nothing specific", "-", "C", "As an event hero, Ice Knight is somewhat difficult to unlock, and very difficult to get medals for. His team buff is increased freeze duration, and many freeze builds do not want that because they rely on freeze explode."],
        "jasmine": [["runeSwift", "frenzy"], "Nothing specific", "Nothing specific", "-", "C", "Jasmine has some use for buffing fire heroes Crit Damage. This is very important for the Guild Slay Event, as critical hits are where most of the damage comes from. It also helps with a fire team in Blitz. She’s also very fast, and can be used in staging."],
        "kage": [["vitality", "runeSwift", "frenzy"], "HP", "Nothing specific", "-", "A", "Kage is generally used for his HP debuff, which is useful in all aspects of the game. If you’re close to beating a new daily dungeon level, you can throw Kage in for some extra % done to the boss. He is essential for any hitter in Slay Boss event."],
        "kasai": [["vitality", "nimble", "precise"], "Nothing specific", "Nothing specific", "-", "C", "Kasai has the 4th highest base DPS, but one of the lowest base HP. His buff is Fire Atk, and most PVP teams prefer universal Atk Buffs."],
        "kasumi": [["vitality", "nimble", "swift"], "HP", "Nothing specific", "-", "A", "Kasumi has an sp2 with teleport, which makes her very fast for staging, and the best Dark staging hero. She also debuffs opponent attack speed, which is useful in PVP. During the Female Rogue Arena week, she can be quite strong. Teleporting into the backline can be disrupting."],
        "krouki": [["damage", "runeSwift", "precise"], "APS, ATK, Crit DMG", "Attack Range", "-", "C", "Krouki has some use for buffing earth heroes Crit Damage. This is very important for the Guild Slay Event, as critical hits are where most of the damage comes from."],
        "krunk": [["damage", "runeSwift", "precise"], "APS, ATK, Crit DMG", "Attack Range", "-", "C", "Krunk is tied for the third most HP in the game. This makes him a backline tank, which isn’t very useful. He does buff Light Atk, which is useful in Blitz. If you’re using Spike, it’s also useful in Arena and GW. He doesn’t need any runes for this buff though."],
        "leafBlade": [["vitality", "phalanx", "nimble"], "HP", "Movement speed, Def", "-", "S", "Leaf Blade is arguably the second best tank in the game. As a knight, he has a shield. But more importantly, he has an Auto-Shield ability, which makes him immune to damage after he falls below a certain %. It is possible to bypass this Auto-Shield if enough damage is applied to kill him, when he is above that %. When combined with Vlad, the Auto-Shield is long enough to mostly refill his health, which means you basically have to kill him twice."],
        "lightKnight": [["vitality", "nimble", "damage"], "Nothing specific", "Nothing specific", "-", "-", "Light Knight is a fast common, so he can be used for staging, but don't spend materials on this hero."],
        "luka": [["noRune"], "Nothing specific", "Nothing specific", "-", "-", "Luka is your first hero! He’s the best water hero for staging. Other than that he can sit comfortably on the bench and jump in as a filler in Blitz. Don't spend materials on this hero.", ["frenzy", "intelligent", "spoiling"], "Nothing specific", "Movement speed", "For staging"],
        "magmus": [["vitality", "damage", "runeSwift"], "HP", "Movement speed, Def", "-", "B", "Magmus is the best Fire Tank."],
        "mechaValken": [["vitality", "runeSwift", "precise", "rage"], "HP", "Movement speed, Def", "-", "C", "Mecha Valken is really good early on but he doesn’t scale as well as others. His team buff is Fire Def, which isn't very useful."],
        "merlinus": [["runeSwift", "precise", "rage"], "APS, ATK, Crit DMG", "Attack Range", "RUNE NOTES", "PVP TIER", "HERO INFO"],


        "sorrow": [["damage", "runeSwift", "precise", "rage"], "APS, ATK, Crit DMG", "Attack Range", "Needs 21,0% to get 750 range", "A", "Sorrow buffs all gunner atk, which then buffs her own damage. Once she gets to 6 star, she will start doing great damage for your team. As a gunner, she ignores 70% of the opponent’s Def, which can be important. Her sp2 has a stun, while useful, it’s not nearly as important as the damage she does. Since her Crusher Chests are very good, it’s generally best if you buy more of these than other Crusher Chests."]
    }


"""
        "Hero nameSafe": [["damage", "runeSwift", "precise", "rage"], "APS, ATK, Crit DMG", "Attack Range", "RUNE NOTES", "PVP TIER", "HERO INFO"],
"""