"""added Type to artifact

Revision ID: 53987f841448
Revises: 043a330e016c
Create Date: 2020-06-07 23:23:41.055830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53987f841448'
down_revision = '043a330e016c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifact', sa.Column('type', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_artifact_type'), 'artifact', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_type'), table_name='artifact')
    op.drop_column('artifact', 'type')
    # ### end Alembic commands ###
