"""safe name

Revision ID: 9332f05cb7d6
Revises: 30228d27a270
Create Date: 2020-05-24 23:49:06.195432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9332f05cb7d6'
down_revision = '30228d27a270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base', sa.Column('nameSafe', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_base_nameSafe'), 'base', ['nameSafe'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_base_nameSafe'), table_name='base')
    op.drop_column('base', 'nameSafe')
    # ### end Alembic commands ###
