"""boss team

Revision ID: a3c8145a6376
Revises: b02c2dd369a4
Create Date: 2020-06-15 15:09:14.340959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c8145a6376'
down_revision = 'b02c2dd369a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('nameSafe', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boss_base_name'), 'boss_base', ['name'], unique=True)
    op.create_index(op.f('ix_boss_base_nameSafe'), 'boss_base', ['nameSafe'], unique=True)
    op.create_table('bossteam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero1', sa.String(length=16), nullable=True),
    sa.Column('hero1dmg', sa.Integer(), nullable=True),
    sa.Column('hero2', sa.String(length=16), nullable=True),
    sa.Column('hero2dmg', sa.Integer(), nullable=True),
    sa.Column('hero3', sa.String(length=16), nullable=True),
    sa.Column('hero3dmg', sa.Integer(), nullable=True),
    sa.Column('hero4', sa.String(length=16), nullable=True),
    sa.Column('hero4dmg', sa.Integer(), nullable=True),
    sa.Column('hero5', sa.String(length=16), nullable=True),
    sa.Column('hero5dmg', sa.Integer(), nullable=True),
    sa.Column('hero6', sa.String(length=16), nullable=True),
    sa.Column('hero6dmg', sa.Integer(), nullable=True),
    sa.Column('hero7', sa.String(length=16), nullable=True),
    sa.Column('hero7dmg', sa.Integer(), nullable=True),
    sa.Column('hero8', sa.String(length=16), nullable=True),
    sa.Column('hero8dmg', sa.Integer(), nullable=True),
    sa.Column('hero9', sa.String(length=16), nullable=True),
    sa.Column('hero9dmg', sa.Integer(), nullable=True),
    sa.Column('hero10', sa.String(length=16), nullable=True),
    sa.Column('hero10dmg', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bossbase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bossbase_id'], ['boss_base.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bossteam_hero1'), 'bossteam', ['hero1'], unique=False)
    op.create_index(op.f('ix_bossteam_hero10'), 'bossteam', ['hero10'], unique=False)
    op.create_index(op.f('ix_bossteam_hero10dmg'), 'bossteam', ['hero10dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero1dmg'), 'bossteam', ['hero1dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero2'), 'bossteam', ['hero2'], unique=False)
    op.create_index(op.f('ix_bossteam_hero2dmg'), 'bossteam', ['hero2dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero3'), 'bossteam', ['hero3'], unique=False)
    op.create_index(op.f('ix_bossteam_hero3dmg'), 'bossteam', ['hero3dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero4'), 'bossteam', ['hero4'], unique=False)
    op.create_index(op.f('ix_bossteam_hero4dmg'), 'bossteam', ['hero4dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero5'), 'bossteam', ['hero5'], unique=False)
    op.create_index(op.f('ix_bossteam_hero5dmg'), 'bossteam', ['hero5dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero6'), 'bossteam', ['hero6'], unique=False)
    op.create_index(op.f('ix_bossteam_hero6dmg'), 'bossteam', ['hero6dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero7'), 'bossteam', ['hero7'], unique=False)
    op.create_index(op.f('ix_bossteam_hero7dmg'), 'bossteam', ['hero7dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero8'), 'bossteam', ['hero8'], unique=False)
    op.create_index(op.f('ix_bossteam_hero8dmg'), 'bossteam', ['hero8dmg'], unique=False)
    op.create_index(op.f('ix_bossteam_hero9'), 'bossteam', ['hero9'], unique=False)
    op.create_index(op.f('ix_bossteam_hero9dmg'), 'bossteam', ['hero9dmg'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bossteam_hero9dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero9'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero8dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero8'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero7dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero7'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero6dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero6'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero5dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero5'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero4dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero4'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero3dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero3'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero2dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero2'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero1dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero10dmg'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero10'), table_name='bossteam')
    op.drop_index(op.f('ix_bossteam_hero1'), table_name='bossteam')
    op.drop_table('bossteam')
    op.drop_index(op.f('ix_boss_base_nameSafe'), table_name='boss_base')
    op.drop_index(op.f('ix_boss_base_name'), table_name='boss_base')
    op.drop_table('boss_base')
    # ### end Alembic commands ###
