"""color of artifacts

Revision ID: b02c2dd369a4
Revises: 53987f841448
Create Date: 2020-06-11 21:39:42.265296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02c2dd369a4'
down_revision = '53987f841448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art_base', sa.Column('color', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_art_base_color'), 'art_base', ['color'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_art_base_color'), table_name='art_base')
    op.drop_column('art_base', 'color')
    # ### end Alembic commands ###
