"""updated Base

Revision ID: e41645aad309
Revises: 9332f05cb7d6
Create Date: 2020-06-03 20:36:04.552316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41645aad309'
down_revision = '9332f05cb7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base', sa.Column('buff', sa.Integer(), nullable=True))
    op.add_column('base', sa.Column('buffElement', sa.String(length=16), nullable=True))
    op.add_column('base', sa.Column('buffStat', sa.String(length=16), nullable=True))
    op.add_column('base', sa.Column('buffType', sa.Integer(), nullable=True))
    op.add_column('base', sa.Column('sp2', sa.Integer(), nullable=True))
    op.add_column('base', sa.Column('sp2num', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_base_buff'), 'base', ['buff'], unique=False)
    op.create_index(op.f('ix_base_buffElement'), 'base', ['buffElement'], unique=False)
    op.create_index(op.f('ix_base_buffStat'), 'base', ['buffStat'], unique=False)
    op.create_index(op.f('ix_base_buffType'), 'base', ['buffType'], unique=False)
    op.create_index(op.f('ix_base_sp2'), 'base', ['sp2'], unique=False)
    op.create_index(op.f('ix_base_sp2num'), 'base', ['sp2num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_base_sp2num'), table_name='base')
    op.drop_index(op.f('ix_base_sp2'), table_name='base')
    op.drop_index(op.f('ix_base_buffType'), table_name='base')
    op.drop_index(op.f('ix_base_buffStat'), table_name='base')
    op.drop_index(op.f('ix_base_buffElement'), table_name='base')
    op.drop_index(op.f('ix_base_buff'), table_name='base')
    op.drop_column('base', 'sp2num')
    op.drop_column('base', 'sp2')
    op.drop_column('base', 'buffType')
    op.drop_column('base', 'buffStat')
    op.drop_column('base', 'buffElement')
    op.drop_column('base', 'buff')
    # ### end Alembic commands ###
